name: graduate_gtudiesV2
description: A new Flutter project.

version: 1.0.0+1

environment:

  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  mime_type: ^1.0.0
  cupertino_icons: ^1.0.2
  uuid: ^4.0.0
  crypto: ^3.0.3
  get: ^4.6.5
  connectivity_plus: ^6.1.0
  getwidget: ^6.0.0
  intl: ^0.20.1
  dropdown_button2: ^2.3.9
  custom_switcher: ^1.0.0
  printing: ^5.11.0
  pdf: ^3.10.4
  pin_code_fields: ^8.0.1
  http: ^1.1.0
  email_auth: ^2.0.0
  authorization_header: ^1.0.3
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  awesome_dialog: ^3.2.0
  lottie: ^3.0.0
  file_picker: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator:



flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Black.ttf
    - family: Hacen
      fonts:
        - asset: assets/fonts/Hacen Tunisia.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
